---
resources:
  - name: assignment-repo
    type: git
    source:
      uri: https://github.com/TeamIO-NZ/SoftwareTestingAssignmentTwo
      branch: master

jobs:
  - name: test
    plan:
      - get: assignment-repo
        trigger: true
      - task: run-tests
        config:
            inputs:
                - name: assignment-repo
            platform: linux
            image_resource: &jdkImage
              type: registry-image
              source:
                repository: "openjdk"
                tag: "11-jdk"
            run:
              path: sh
              args: 
              - -exc
              - |
                cd assignment-repo
                ./gradlew test --stacktrace

  - name: build
    plan:
      - get: assignment-repo
        passed: [test]
        trigger: true
      - task: run-build
        config:
            inputs:
                - name: assignment-repo
            platform: linux
            image_resource: *jdkImage
            run:
              path: sh
              args: 
              - -exc
              - |
                cd assignment-repo
                ./gradlew build --stacktrace